// Generated by CoffeeScript 1.6.3
(function() {
  var infos, manfred, merge;

  infos = require('./infos');

  merge = require('./utils').merge;

  module.exports = manfred = function() {
    return console.log("" + manfred.fullname + " <" + manfred.mail + ">");
  };

  manfred.__defineGetter__('fullname', function() {
    return "" + manfred.firstname + " " + manfred.lastname;
  });

  merge(manfred, infos);

}).call(this);
