// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    firstname: 'Manfred',
    lastname: 'Touron',
    mail: 'm@42.am',
    birthdate: '01/25/1988',
    country: 'France',
    city: 'Paris',
    company: 'Online OCS (Iliad)',
    alumni: ['Epitech'],
    networks: ['While42', '42am'],
    links: ['https://moul.github.io/']
  };

}).call(this);
